SELECT id,
       user_id,
       "number",
       total_amount,
       "time",
       "date",
       llm_name,
       currency_code,
       payment_method,
       "status",
       llm_text_response,
       seller_info,
       items,
       created_at,
       updated_at,
       searchable_content,
       embedding_generated_at,
       embedding_model,
       metadata,
       content_embedding
FROM public.invoices
LIMIT 1000;
